import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./styles/globals.css";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "flex flex-col justify-center relative min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        
        {children}
        </body>
    </html>
  );
}
